<?php
/**
 * Static map of PHP extension symbols (functions and classes).
 *
 * This map lets the scanner recognize extension requirements even when the
 * extension is NOT loaded in the PHP environment running the scanner —
 * which is the whole point of being able to flag "you need to enable X".
 *
 * The list favors precision over completeness: it curates the commonly
 * used, unambiguous, extension-specific symbols for each extension. It is
 * not a full reproduction of every function/class PHP ships (that list
 * runs into the thousands and is better sourced from php-src stubs, e.g.
 * via `mglnet/composer-require-checker`'s generated data). Symbols that
 * are ambiguous with common user-defined names are intentionally left out
 * to avoid false positives.
 *
 * Structure:
 *
 *     'extension-name' => [
 *         'functions' => [ 'func_one', 'func_two', ... ],
 *         'classes'   => [ 'ClassOne', 'ClassTwo', ... ],
 *     ]
 *
 * Extension names match the names Composer/PHP use for `ext-*` (e.g.
 * 'curl' => ext-curl, 'pdo_mysql' => ext-pdo_mysql).
 *
 * @package SmartLicenseServer\Tools
 */

return [
	'curl'        => [
		'functions' => [
			'curl_close', 'curl_copy_handle', 'curl_errno', 'curl_error',
			'curl_escape', 'curl_exec', 'curl_file_create', 'curl_getinfo',
			'curl_init', 'curl_multi_add_handle', 'curl_multi_close',
			'curl_multi_exec', 'curl_multi_getcontent', 'curl_multi_info_read',
			'curl_multi_init', 'curl_multi_remove_handle', 'curl_multi_select',
			'curl_multi_setopt', 'curl_multi_strerror', 'curl_pause',
			'curl_reset', 'curl_setopt', 'curl_setopt_array', 'curl_share_close',
			'curl_share_init', 'curl_share_setopt', 'curl_strerror',
			'curl_unescape', 'curl_upkeep', 'curl_version',
		],
		'classes'   => [ 'CurlHandle', 'CurlMultiHandle', 'CurlShareHandle', 'CURLFile', 'CURLStringFile' ],
	],
	'gd'          => [
		'functions' => [
			'gd_info', 'imageaffine', 'imagealphablending', 'imageantialias',
			'imagearc', 'imagechar', 'imagecharup', 'imagecolorallocate',
			'imagecolorallocatealpha', 'imagecolorat', 'imagecolorclosest',
			'imagecolorclosestalpha', 'imagecolordeallocate', 'imagecolorexact',
			'imagecolormatch', 'imagecolorresolve', 'imagecolorset',
			'imagecolorsforindex', 'imagecolorstotal', 'imagecolortransparent',
			'imageconvolution', 'imagecopy', 'imagecopymerge',
			'imagecopymergegray', 'imagecopyresampled', 'imagecopyresized',
			'imagecreate', 'imagecreatefromgd2', 'imagecreatefromgd2part',
			'imagecreatefromgd', 'imagecreatefromgif', 'imagecreatefromjpeg',
			'imagecreatefrompng', 'imagecreatefromstring', 'imagecreatefromwebp',
			'imagecreatefrombmp', 'imagecreatefromwbmp', 'imagecreatefromxbm',
			'imagecreatefromxpm', 'imagecreatetruecolor', 'imagecrop',
			'imagecropauto', 'imagedashedline', 'imagedestroy', 'imageellipse',
			'imagefill', 'imagefilledarc', 'imagefilledellipse',
			'imagefilledpolygon', 'imagefilledrectangle', 'imagefilltoborder',
			'imagefilter', 'imageflip', 'imagefontheight', 'imagefontwidth',
			'imageftbbox', 'imagefttext', 'imagegammacorrect', 'imagegd2',
			'imagegd', 'imagegetclip', 'imagegif', 'imagegrabscreen',
			'imagegrabwindow', 'imageinterlace', 'imageistruecolor', 'imagejpeg',
			'imagelayereffect', 'imageline', 'imageloadfont', 'imageopenpolygon',
			'imagepalettecopy', 'imagepalettetotruecolor', 'imagepng',
			'imagepolygon', 'imagerectangle', 'imagerotate', 'imagesavealpha',
			'imagescale', 'imagesetbrush', 'imagesetclip', 'imagesetinterpolation',
			'imagesetpixel', 'imagesetstyle', 'imagesetthickness',
			'imagesettile', 'imagestring', 'imagestringup', 'imagesx',
			'imagesy', 'imagetruecolortopalette', 'imagettfbbox', 'imagettftext',
			'imagetypes', 'imagewbmp', 'imagewebp', 'imagexbm',
			'iptcembed', 'iptcparse', 'jpeg2wbmp', 'png2wbmp',
		],
		'classes'   => [ 'GdImage', 'GdFont' ],
	],
	'imagick'     => [
		'functions' => [],
		'classes'   => [ 'Imagick', 'ImagickDraw', 'ImagickPixel', 'ImagickPixelIterator', 'ImagickKernel', 'ImagickException', 'ImagickDrawException', 'ImagickPixelException', 'ImagickPixelIteratorException' ],
	],
	'mbstring'    => [
		'functions' => [
			'mb_check_encoding', 'mb_chr', 'mb_convert_case', 'mb_convert_encoding',
			'mb_convert_kana', 'mb_convert_variables', 'mb_decode_mimeheader',
			'mb_decode_numericentity', 'mb_detect_encoding', 'mb_detect_order',
			'mb_encode_mimeheader', 'mb_encode_numericentity',
			'mb_encoding_aliases', 'mb_ereg_match', 'mb_ereg_replace_callback',
			'mb_ereg_replace', 'mb_ereg_search_getpos', 'mb_ereg_search_getregs',
			'mb_ereg_search_init', 'mb_ereg_search_pos', 'mb_ereg_search_regs',
			'mb_ereg_search_setpos', 'mb_ereg_search', 'mb_ereg',
			'mb_eregi_replace', 'mb_eregi', 'mb_get_info',
			'mb_http_input', 'mb_http_output', 'mb_internal_encoding',
			'mb_language', 'mb_lcfirst', 'mb_list_encodings', 'mb_ord',
			'mb_output_handler', 'mb_parse_str', 'mb_preferred_mime_name',
			'mb_regex_encoding', 'mb_regex_set_options', 'mb_scrub',
			'mb_send_mail', 'mb_split', 'mb_str_pad', 'mb_str_split',
			'mb_strcut', 'mb_strimwidth', 'mb_stripos', 'mb_stristr',
			'mb_strlen', 'mb_strpos', 'mb_strrchr', 'mb_strrichr',
			'mb_strripos', 'mb_strrpos', 'mb_strstr', 'mb_strtolower',
			'mb_strtoupper', 'mb_strwidth', 'mb_substitute_character',
			'mb_substr_count', 'mb_substr', 'mb_ucfirst', 'mb_ucwords',
		],
		'classes'   => [],
	],
	'zip'         => [
		'functions' => [ 'zip_close', 'zip_entry_close', 'zip_entry_compressedsize', 'zip_entry_compressionmethod', 'zip_entry_filesize', 'zip_entry_name', 'zip_entry_open', 'zip_entry_read', 'zip_open', 'zip_read' ],
		'classes'   => [ 'ZipArchive', 'PharData' ],
	],
	'intl'        => [
		'functions' => [
			'collator_asort', 'collator_compare', 'collator_create',
			'collator_get_attribute', 'collator_get_error_code',
			'collator_get_error_message', 'collator_get_locale',
			'collator_get_sort_key', 'collator_get_strength',
			'collator_set_attribute', 'collator_set_strength',
			'collator_sort_with_sort_keys', 'collator_sort',
			'datefmt_create', 'datefmt_format', 'datefmt_get_locale',
			'datefmt_get_timezone', 'datefmt_parse', 'datefmt_set_pattern',
			'datefmt_set_timezone', 'grapheme_extract', 'grapheme_strlen',
			'grapheme_strpos', 'grapheme_strripos', 'grapheme_strrpos',
			'grapheme_stristr', 'grapheme_strstr', 'grapheme_substr',
			'idn_to_ascii', 'idn_to_utf8', 'intltz_create_default',
			'intltz_get_id', 'locale_accept_from_http', 'locale_canonicalize',
			'locale_compose', 'locale_filter_matches', 'locale_get_all_variants',
			'locale_get_default', 'locale_get_display_language',
			'locale_get_display_name', 'locale_get_display_region',
			'locale_get_display_script', 'locale_get_display_variant',
			'locale_get_keywords', 'locale_get_primary_language',
			'locale_get_region', 'locale_get_script', 'locale_lookup',
			'locale_parse', 'locale_set_default', 'msgfmt_create',
			'msgfmt_format', 'msgfmt_parse', 'normalizer_is_normalized',
			'normalizer_normalize', 'numfmt_create', 'numfmt_format',
			'numfmt_parse', 'resourcebundle_create', 'resourcebundle_get',
			'resourcebundle_locales', 'transliterator_create',
			'transliterator_transliterate',
		],
		'classes'   => [
			'Collator', 'DateFormatter', 'IntlCalendar', 'IntlChar',
			'IntlDateFormatter', 'IntlTimeZone', 'Locale', 'MessageFormatter',
			'NumberFormatter', 'ResourceBundle', 'Spoofchecker', 'Transliterator',
			'UConverter', 'IntlException', 'IntlBreakIterator', 'IntlPartsIterator',
			'IntlCodePointBreakIterator', 'IntlRuleBasedBreakIterator', 'IntlIterator',
		],
	],
	'fileinfo'    => [
		'functions' => [ 'finfo_buffer', 'finfo_close', 'finfo_open', 'finfo_set_flags', 'mime_content_type' ],
		'classes'   => [ 'finfo' ],
	],
	'exif'        => [
		'functions' => [ 'exif_imagetype', 'exif_read_data', 'exif_tagname', 'exif_thumbnail', 'read_exif_data' ],
		'classes'   => [],
	],
	'ftp'         => [
		'functions' => [
			'ftp_alloc', 'ftp_append', 'ftp_cdup', 'ftp_chdir', 'ftp_chmod',
			'ftp_close', 'ftp_connect', 'ftp_delete', 'ftp_exec', 'ftp_fget',
			'ftp_fput', 'ftp_get_option', 'ftp_get', 'ftp_login', 'ftp_mdtm',
			'ftp_mkdir', 'ftp_mlsd', 'ftp_nb_continue', 'ftp_nb_fget',
			'ftp_nb_fput', 'ftp_nb_get', 'ftp_nb_put', 'ftp_nlist', 'ftp_pasv',
			'ftp_put', 'ftp_pwd', 'ftp_quit', 'ftp_raw', 'ftp_rawlist',
			'ftp_rename', 'ftp_rmdir', 'ftp_set_option', 'ftp_site', 'ftp_size',
			'ftp_ssl_connect', 'ftp_systype',
		],
		'classes'   => [ 'FTP\\Connection' ],
	],
	'sockets'     => [
		'functions' => [
			'socket_accept', 'socket_addrinfo_bind', 'socket_addrinfo_connect',
			'socket_addrinfo_explain', 'socket_addrinfo_lookup', 'socket_bind',
			'socket_clear_error', 'socket_close', 'socket_cmsg_space',
			'socket_connect', 'socket_create_listen', 'socket_create_pair',
			'socket_create', 'socket_export_stream', 'socket_get_option',
			'socket_getopt', 'socket_getpeername', 'socket_getsockname',
			'socket_import_stream', 'socket_last_error', 'socket_listen',
			'socket_read', 'socket_recv', 'socket_recvfrom', 'socket_recvmsg',
			'socket_select', 'socket_send', 'socket_sendmsg', 'socket_sendto',
			'socket_set_block', 'socket_set_nonblock', 'socket_set_option',
			'socket_setopt', 'socket_shutdown', 'socket_strerror', 'socket_write',
			'socket_wsaprotocol_info_export', 'socket_wsaprotocol_info_import',
			'socket_wsaprotocol_info_release',
		],
		'classes'   => [ 'Socket', 'AddressInfo' ],
	],
	'ldap'        => [
		'functions' => [
			'ldap_add_ext', 'ldap_add', 'ldap_bind_ext', 'ldap_bind',
			'ldap_close', 'ldap_compare', 'ldap_connect', 'ldap_control_paged_result',
			'ldap_count_entries', 'ldap_count_references', 'ldap_delete_ext',
			'ldap_delete', 'ldap_dn2ufn', 'ldap_err2str', 'ldap_errno',
			'ldap_error', 'ldap_escape', 'ldap_exop', 'ldap_explode_dn',
			'ldap_first_attribute', 'ldap_first_entry', 'ldap_first_reference',
			'ldap_free_result', 'ldap_get_attributes', 'ldap_get_dn',
			'ldap_get_entries', 'ldap_get_option', 'ldap_get_values_len',
			'ldap_get_values', 'ldap_list', 'ldap_mod_add_ext', 'ldap_mod_add',
			'ldap_mod_del_ext', 'ldap_mod_del', 'ldap_mod_replace_ext',
			'ldap_mod_replace', 'ldap_modify_batch', 'ldap_next_attribute',
			'ldap_next_entry', 'ldap_next_reference', 'ldap_parse_exop',
			'ldap_parse_reference', 'ldap_parse_result', 'ldap_read',
			'ldap_rename_ext', 'ldap_rename', 'ldap_sasl_bind', 'ldap_search',
			'ldap_set_option', 'ldap_set_rebind_proc', 'ldap_start_tls',
			'ldap_unbind',
		],
		'classes'   => [ 'LDAP\\Connection', 'LDAP\\Result', 'LDAP\\ResultEntry' ],
	],
	'imap'        => [
		'functions' => [
			'imap_8bit', 'imap_alerts', 'imap_append', 'imap_base64',
			'imap_binary', 'imap_body', 'imap_bodystruct', 'imap_check',
			'imap_clearflag_full', 'imap_close', 'imap_create', 'imap_createmailbox',
			'imap_delete', 'imap_deletemailbox', 'imap_errors', 'imap_expunge',
			'imap_fetch_overview', 'imap_fetchbody', 'imap_fetchheader',
			'imap_fetchmime', 'imap_fetchstructure', 'imap_fetchtext',
			'imap_gc', 'imap_get_quota', 'imap_get_quotaroot', 'imap_getacl',
			'imap_getmailboxes', 'imap_getsubscribed', 'imap_header',
			'imap_headerinfo', 'imap_headers', 'imap_last_error', 'imap_list',
			'imap_listmailbox', 'imap_listscan', 'imap_listsubscribed',
			'imap_lsub', 'imap_mail_compose', 'imap_mail_copy', 'imap_mail_move',
			'imap_mail', 'imap_mailboxmsginfo', 'imap_mime_header_decode',
			'imap_msgno', 'imap_num_msg', 'imap_num_recent', 'imap_open',
			'imap_ping', 'imap_qprint', 'imap_rename', 'imap_renamemailbox',
			'imap_reopen', 'imap_rfc822_parse_adrlist', 'imap_rfc822_parse_headers',
			'imap_rfc822_write_address', 'imap_savebody', 'imap_scan',
			'imap_scanmailbox', 'imap_search', 'imap_set_quota', 'imap_setacl',
			'imap_setflag_full', 'imap_sort', 'imap_status', 'imap_subscribe',
			'imap_thread', 'imap_timeout', 'imap_uid', 'imap_undelete',
			'imap_unsubscribe', 'imap_utf7_decode', 'imap_utf7_encode',
			'imap_utf8',
		],
		'classes'   => [],
	],
	'bcmath'      => [
		'functions' => [
			'bcadd', 'bccomp', 'bcdiv', 'bcmod', 'bcmul', 'bcpow', 'bcpowmod',
			'bcscale', 'bcsqrt', 'bcsub', 'bcceil', 'bcfloor', 'bcround',
			'bcdivmod',
		],
		'classes'   => [ 'BcMath\\Number' ],
	],
	'gmp'         => [
		'functions' => [
			'gmp_abs', 'gmp_add', 'gmp_and', 'gmp_binomial', 'gmp_clrbit',
			'gmp_cmp', 'gmp_com', 'gmp_div_q', 'gmp_div_qr', 'gmp_div_r',
			'gmp_div', 'gmp_divexact', 'gmp_export', 'gmp_fact', 'gmp_gcd',
			'gmp_gcdext', 'gmp_hamdist', 'gmp_import', 'gmp_init', 'gmp_intval',
			'gmp_invert', 'gmp_jacobi', 'gmp_kronecker', 'gmp_lcm', 'gmp_legendre',
			'gmp_mod', 'gmp_mul', 'gmp_neg', 'gmp_nextprime', 'gmp_or',
			'gmp_perfect_power', 'gmp_perfect_square', 'gmp_popcount', 'gmp_pow',
			'gmp_powm', 'gmp_prob_prime', 'gmp_random_bits', 'gmp_random_range',
			'gmp_random_seed', 'gmp_random', 'gmp_root', 'gmp_rootrem',
			'gmp_scan0', 'gmp_scan1', 'gmp_setbit', 'gmp_sign', 'gmp_sqrt',
			'gmp_sqrtrem', 'gmp_strval', 'gmp_sub', 'gmp_testbit', 'gmp_xor',
		],
		'classes'   => [ 'GMP' ],
	],
	'sodium'      => [
		'functions' => [
			'sodium_add', 'sodium_base642bin', 'sodium_bin2base64', 'sodium_bin2hex',
			'sodium_compare', 'sodium_crypto_aead_aes256gcm_decrypt',
			'sodium_crypto_aead_aes256gcm_encrypt', 'sodium_crypto_aead_chacha20poly1305_decrypt',
			'sodium_crypto_aead_chacha20poly1305_encrypt',
			'sodium_crypto_aead_chacha20poly1305_ietf_decrypt',
			'sodium_crypto_aead_chacha20poly1305_ietf_encrypt',
			'sodium_crypto_aead_xchacha20poly1305_ietf_decrypt',
			'sodium_crypto_aead_xchacha20poly1305_ietf_encrypt', 'sodium_crypto_auth',
			'sodium_crypto_auth_verify', 'sodium_crypto_box', 'sodium_crypto_box_keypair',
			'sodium_crypto_box_open', 'sodium_crypto_box_publickey',
			'sodium_crypto_box_secretkey', 'sodium_crypto_box_seal',
			'sodium_crypto_box_seal_open', 'sodium_crypto_generichash',
			'sodium_crypto_kdf_derive_from_key', 'sodium_crypto_kx_keypair',
			'sodium_crypto_pwhash', 'sodium_crypto_pwhash_str',
			'sodium_crypto_pwhash_str_verify', 'sodium_crypto_secretbox',
			'sodium_crypto_secretbox_open', 'sodium_crypto_shorthash',
			'sodium_crypto_sign', 'sodium_crypto_sign_detached',
			'sodium_crypto_sign_keypair', 'sodium_crypto_sign_open',
			'sodium_crypto_sign_publickey', 'sodium_crypto_sign_secretkey',
			'sodium_crypto_sign_verify_detached', 'sodium_crypto_stream',
			'sodium_crypto_stream_xor', 'sodium_hex2bin', 'sodium_increment',
			'sodium_memcmp', 'sodium_memzero', 'sodium_pad', 'sodium_unpad',
		],
		'classes'   => [],
	],
	'apcu'        => [
		'functions' => [
			'apcu_add', 'apcu_cache_info', 'apcu_cas', 'apcu_clear_cache',
			'apcu_dec', 'apcu_delete', 'apcu_enabled', 'apcu_entry', 'apcu_exists',
			'apcu_fetch', 'apcu_inc', 'apcu_key_info', 'apcu_sma_info', 'apcu_store',
		],
		'classes'   => [ 'APCUIterator' ],
	],
	'redis'       => [
		'functions' => [],
		'classes'   => [ 'Redis', 'RedisCluster', 'RedisSentinel', 'RedisArray', 'RedisException', 'RedisClusterException' ],
	],
	'memcached'   => [
		'functions' => [],
		'classes'   => [ 'Memcached', 'MemcachedException' ],
	],
	'memcache'    => [
		'functions' => [
			'memcache_add', 'memcache_connect', 'memcache_debug', 'memcache_delete',
			'memcache_get', 'memcache_pconnect', 'memcache_set',
		],
		'classes'   => [ 'Memcache' ],
	],
	'mongodb'     => [
		'functions' => [],
		'classes'   => [
			'MongoDB\\Driver\\Manager', 'MongoDB\\Driver\\Query', 'MongoDB\\Driver\\BulkWrite',
			'MongoDB\\Driver\\Command', 'MongoDB\\Driver\\Cursor', 'MongoDB\\Driver\\Server',
			'MongoDB\\Driver\\Session', 'MongoDB\\Driver\\WriteConcern', 'MongoDB\\Driver\\ReadPreference',
			'MongoDB\\BSON\\ObjectId', 'MongoDB\\BSON\\UTCDateTime', 'MongoDB\\BSON\\Document',
		],
	],
	'amqp'        => [
		'functions' => [],
		'classes'   => [ 'AMQPConnection', 'AMQPChannel', 'AMQPExchange', 'AMQPQueue', 'AMQPEnvelope', 'AMQPException' ],
	],
	'yaml'        => [
		'functions' => [ 'yaml_emit_file', 'yaml_emit', 'yaml_parse_file', 'yaml_parse_url', 'yaml_parse' ],
		'classes'   => [],
	],
	'msgpack'     => [
		'functions' => [ 'msgpack_pack', 'msgpack_serialize', 'msgpack_unpack', 'msgpack_unserialize', 'msgpack_unpacker' ],
		'classes'   => [ 'MessagePack', 'MessagePackUnpacker' ],
	],
	'event'       => [
		'functions' => [],
		'classes'   => [ 'Event', 'EventBase', 'EventBuffer', 'EventBufferEvent', 'EventConfig', 'EventListener', 'EventSslContext', 'EventHttp', 'EventHttpConnection', 'EventHttpRequest' ],
	],
	'swoole'      => [
		'functions' => [],
		'classes'   => [ 'Swoole\\Server', 'Swoole\\Client', 'Swoole\\Http\\Server', 'Swoole\\WebSocket\\Server', 'Swoole\\Coroutine', 'Swoole\\Process', 'Swoole\\Table', 'Swoole\\Timer' ],
	],
	'xdebug'      => [
		'functions' => [
			'xdebug_break', 'xdebug_call_class', 'xdebug_call_file',
			'xdebug_call_function', 'xdebug_call_line', 'xdebug_code_coverage_started',
			'xdebug_connect_to_client', 'xdebug_debug_zval', 'xdebug_dump_superglobals',
			'xdebug_get_code_coverage', 'xdebug_get_collected_errors',
			'xdebug_get_function_stack', 'xdebug_get_headers', 'xdebug_get_monitored_functions',
			'xdebug_get_profiler_filename', 'xdebug_get_stack_depth',
			'xdebug_get_tracefile_name', 'xdebug_info', 'xdebug_is_debugger_active',
			'xdebug_memory_usage', 'xdebug_notify', 'xdebug_peak_memory_usage',
			'xdebug_print_function_stack', 'xdebug_start_code_coverage',
			'xdebug_start_error_collection', 'xdebug_start_function_monitor',
			'xdebug_start_trace', 'xdebug_stop_code_coverage', 'xdebug_stop_error_collection',
			'xdebug_stop_function_monitor', 'xdebug_stop_trace', 'xdebug_time_index',
		],
		'classes'   => [],
	],
	'pdo_mysql'   => [ 'functions' => [], 'classes' => [] ],
	'pdo_pgsql'   => [ 'functions' => [], 'classes' => [] ],
	'pdo_sqlite'  => [ 'functions' => [], 'classes' => [] ],
	'pdo_sqlsrv'  => [ 'functions' => [], 'classes' => [] ],
	'mysqli'      => [
		'functions' => [
			'mysqli_affected_rows', 'mysqli_autocommit', 'mysqli_begin_transaction',
			'mysqli_change_user', 'mysqli_character_set_name', 'mysqli_close',
			'mysqli_commit', 'mysqli_connect_errno', 'mysqli_connect_error',
			'mysqli_connect', 'mysqli_data_seek', 'mysqli_debug', 'mysqli_dump_debug_info',
			'mysqli_errno', 'mysqli_error_list', 'mysqli_error', 'mysqli_escape_string',
			'mysqli_execute_query', 'mysqli_fetch_all', 'mysqli_fetch_array',
			'mysqli_fetch_assoc', 'mysqli_fetch_column', 'mysqli_fetch_field_direct',
			'mysqli_fetch_field', 'mysqli_fetch_fields', 'mysqli_fetch_lengths',
			'mysqli_fetch_object', 'mysqli_fetch_row', 'mysqli_field_count',
			'mysqli_field_seek', 'mysqli_field_tell', 'mysqli_free_result',
			'mysqli_get_charset', 'mysqli_get_client_info', 'mysqli_get_client_stats',
			'mysqli_get_client_version', 'mysqli_get_connection_stats',
			'mysqli_get_host_info', 'mysqli_get_links_stats', 'mysqli_get_proto_info',
			'mysqli_get_server_info', 'mysqli_get_server_version', 'mysqli_get_warnings',
			'mysqli_init', 'mysqli_insert_id', 'mysqli_kill', 'mysqli_more_results',
			'mysqli_multi_query', 'mysqli_next_result', 'mysqli_num_fields',
			'mysqli_num_rows', 'mysqli_options', 'mysqli_ping', 'mysqli_poll',
			'mysqli_prepare', 'mysqli_query', 'mysqli_real_connect', 'mysqli_real_escape_string',
			'mysqli_real_query', 'mysqli_reap_async_query', 'mysqli_refresh',
			'mysqli_release_savepoint', 'mysqli_rollback', 'mysqli_savepoint',
			'mysqli_select_db', 'mysqli_set_charset', 'mysqli_set_local_infile_default',
			'mysqli_set_local_infile_handler', 'mysqli_ssl_set', 'mysqli_stat',
			'mysqli_stmt_affected_rows', 'mysqli_stmt_attr_get', 'mysqli_stmt_attr_set',
			'mysqli_stmt_bind_param', 'mysqli_stmt_bind_result', 'mysqli_stmt_close',
			'mysqli_stmt_data_seek', 'mysqli_stmt_errno', 'mysqli_stmt_error_list',
			'mysqli_stmt_error', 'mysqli_stmt_execute', 'mysqli_stmt_fetch',
			'mysqli_stmt_field_count', 'mysqli_stmt_free_result', 'mysqli_stmt_get_result',
			'mysqli_stmt_get_warnings', 'mysqli_stmt_init', 'mysqli_stmt_insert_id',
			'mysqli_stmt_more_results', 'mysqli_stmt_next_result', 'mysqli_stmt_num_rows',
			'mysqli_stmt_param_count', 'mysqli_stmt_prepare', 'mysqli_stmt_reset',
			'mysqli_stmt_result_metadata', 'mysqli_stmt_send_long_data',
			'mysqli_stmt_sqlstate', 'mysqli_store_result', 'mysqli_thread_id',
			'mysqli_thread_safe', 'mysqli_use_result', 'mysqli_warning_count',
		],
		'classes'   => [ 'mysqli', 'mysqli_stmt', 'mysqli_result', 'mysqli_driver', 'mysqli_warning', 'mysqli_sql_exception' ],
	],
	'pgsql'       => [
		'functions' => [
			'pg_affected_rows', 'pg_cancel_query', 'pg_client_encoding',
			'pg_close', 'pg_connect', 'pg_connection_status', 'pg_convert',
			'pg_copy_from', 'pg_copy_to', 'pg_dbname', 'pg_delete', 'pg_end_copy',
			'pg_escape_bytea', 'pg_escape_identifier', 'pg_escape_literal',
			'pg_escape_string', 'pg_execute', 'pg_fetch_all_columns', 'pg_fetch_all',
			'pg_fetch_array', 'pg_fetch_assoc', 'pg_fetch_object', 'pg_fetch_result',
			'pg_fetch_row', 'pg_field_is_null', 'pg_field_name', 'pg_field_num',
			'pg_field_prtlen', 'pg_field_size', 'pg_field_table', 'pg_field_type_oid',
			'pg_field_type', 'pg_free_result', 'pg_get_notify', 'pg_get_pid',
			'pg_get_result', 'pg_host', 'pg_insert', 'pg_last_error',
			'pg_last_notice', 'pg_last_oid', 'pg_lo_close', 'pg_lo_create',
			'pg_lo_export', 'pg_lo_import', 'pg_lo_open', 'pg_lo_read_all',
			'pg_lo_read', 'pg_lo_seek', 'pg_lo_tell', 'pg_lo_truncate',
			'pg_lo_unlink', 'pg_lo_write', 'pg_meta_data', 'pg_num_fields',
			'pg_num_rows', 'pg_options', 'pg_parameter_status', 'pg_pconnect',
			'pg_ping', 'pg_port', 'pg_prepare', 'pg_put_line', 'pg_query_params',
			'pg_query', 'pg_result_error_field', 'pg_result_error', 'pg_result_seek',
			'pg_result_status', 'pg_select', 'pg_send_execute', 'pg_send_prepare',
			'pg_send_query_params', 'pg_send_query', 'pg_set_client_encoding',
			'pg_set_error_verbosity', 'pg_trace', 'pg_transaction_status',
			'pg_tty', 'pg_unescape_bytea', 'pg_untrace', 'pg_update', 'pg_version',
		],
		'classes'   => [ 'PgSql\\Connection', 'PgSql\\Result', 'PgSql\\Lob' ],
	],
	'sqlite3'     => [
		'functions' => [ 'sqlite_escape_string' ],
		'classes'   => [ 'SQLite3', 'SQLite3Stmt', 'SQLite3Result', 'SQLite3Exception' ],
	],
	'soap'        => [
		'functions' => [ 'use_soap_error_handler', 'is_soap_fault' ],
		'classes'   => [ 'SoapClient', 'SoapServer', 'SoapFault', 'SoapHeader', 'SoapParam', 'SoapVar' ],
	],
	'dom'         => [
		'functions' => [],
		'classes'   => [
			'DOMDocument', 'DOMElement', 'DOMNode', 'DOMNodeList', 'DOMAttr',
			'DOMText', 'DOMComment', 'DOMCdataSection', 'DOMXPath', 'DOMImplementation',
			'DOMNamedNodeMap', 'DOMCharacterData', 'DOMProcessingInstruction',
			'DOMDocumentFragment', 'DOMEntity', 'DOMEntityReference', 'DOMNotation',
			'DOMException', 'DOMStringExtend', 'DOMDocumentType',
		],
	],
	'simplexml'   => [
		'functions' => [ 'simplexml_import_dom', 'simplexml_load_file', 'simplexml_load_string' ],
		'classes'   => [ 'SimpleXMLElement', 'SimpleXMLIterator' ],
	],
	'xml'         => [
		'functions' => [
			'utf8_decode', 'utf8_encode', 'xml_error_string', 'xml_get_current_byte_index',
			'xml_get_current_column_number', 'xml_get_current_line_number',
			'xml_get_error_code', 'xml_parse_into_struct', 'xml_parse',
			'xml_parser_create_ns', 'xml_parser_create', 'xml_parser_free',
			'xml_parser_get_option', 'xml_parser_set_option',
			'xml_set_character_data_handler', 'xml_set_default_handler',
			'xml_set_element_handler', 'xml_set_end_namespace_decl_handler',
			'xml_set_external_entity_ref_handler', 'xml_set_notation_decl_handler',
			'xml_set_object', 'xml_set_processing_instruction_handler',
			'xml_set_start_namespace_decl_handler', 'xml_set_unparsed_entity_decl_handler',
		],
		'classes'   => [ 'XMLParser' ],
	],
	'xmlwriter'   => [
		'functions' => [
			'xmlwriter_end_attribute', 'xmlwriter_end_cdata', 'xmlwriter_end_comment',
			'xmlwriter_end_document', 'xmlwriter_end_dtd_attlist', 'xmlwriter_end_dtd_element',
			'xmlwriter_end_dtd_entity', 'xmlwriter_end_dtd', 'xmlwriter_end_element',
			'xmlwriter_end_pi', 'xmlwriter_flush', 'xmlwriter_full_end_element',
			'xmlwriter_open_memory', 'xmlwriter_open_uri', 'xmlwriter_output_memory',
			'xmlwriter_set_indent_string', 'xmlwriter_set_indent',
			'xmlwriter_start_attribute_ns', 'xmlwriter_start_attribute',
			'xmlwriter_start_cdata', 'xmlwriter_start_comment', 'xmlwriter_start_document',
			'xmlwriter_start_dtd_attlist', 'xmlwriter_start_dtd_element',
			'xmlwriter_start_dtd_entity', 'xmlwriter_start_dtd', 'xmlwriter_start_element_ns',
			'xmlwriter_start_element', 'xmlwriter_start_pi', 'xmlwriter_text',
			'xmlwriter_write_attribute_ns', 'xmlwriter_write_attribute',
			'xmlwriter_write_cdata', 'xmlwriter_write_comment', 'xmlwriter_write_dtd_attlist',
			'xmlwriter_write_dtd_element', 'xmlwriter_write_dtd_entity',
			'xmlwriter_write_dtd', 'xmlwriter_write_element_ns', 'xmlwriter_write_element',
			'xmlwriter_write_pi', 'xmlwriter_write_raw',
		],
		'classes'   => [ 'XMLWriter' ],
	],
	'xmlreader'   => [
		'functions' => [],
		'classes'   => [ 'XMLReader' ],
	],
	'xsl'         => [
		'functions' => [],
		'classes'   => [ 'XSLTProcessor' ],
	],
	'tidy'        => [
		'functions' => [
			'ob_tidyhandler', 'tidy_access_count', 'tidy_config_count',
			'tidy_error_count', 'tidy_get_error_buffer', 'tidy_get_output',
			'tidy_load_config', 'tidy_reset_config', 'tidy_save_config',
			'tidy_set_encoding', 'tidy_setopt', 'tidy_warning_count',
		],
		'classes'   => [ 'tidy', 'tidyNode' ],
	],
	'gnupg'       => [
		'functions' => [
			'gnupg_adddecryptkey', 'gnupg_addencryptkey', 'gnupg_addsignkey',
			'gnupg_cleardecryptkeys', 'gnupg_clearencryptkeys', 'gnupg_clearsignkeys',
			'gnupg_decrypt', 'gnupg_decryptverify', 'gnupg_encrypt',
			'gnupg_encryptsign', 'gnupg_export', 'gnupg_geterror', 'gnupg_getprotocol',
			'gnupg_import', 'gnupg_init', 'gnupg_keyinfo', 'gnupg_setarmor',
			'gnupg_seterrormode', 'gnupg_setsignmode', 'gnupg_sign', 'gnupg_verify',
		],
		'classes'   => [ 'gnupg' ],
	],
	'bz2'         => [
		'functions' => [
			'bzclose', 'bzcompress', 'bzdecompress', 'bzerrno', 'bzerror',
			'bzerrstr', 'bzflush', 'bzopen', 'bzread', 'bzwrite',
		],
		'classes'   => [],
	],
	'ctype'       => [
		'functions' => [
			'ctype_alnum', 'ctype_alpha', 'ctype_cntrl', 'ctype_digit',
			'ctype_graph', 'ctype_lower', 'ctype_print', 'ctype_punct',
			'ctype_space', 'ctype_upper', 'ctype_xdigit',
		],
		'classes'   => [],
	],
	'iconv'       => [
		'functions' => [
			'iconv_get_encoding', 'iconv_mime_decode_headers', 'iconv_mime_decode',
			'iconv_mime_encode', 'iconv_set_encoding', 'iconv_strlen', 'iconv_strpos',
			'iconv_strrpos', 'iconv_substr', 'iconv',
		],
		'classes'   => [],
	],
	'gettext'     => [
		'functions' => [
			'bind_textdomain_codeset', 'bindtextdomain', 'dcgettext', 'dcngettext',
			'dgettext', 'dngettext', 'gettext', 'ngettext', 'textdomain',
		],
		'classes'   => [],
	],
	'fpm'         => [
		'functions' => [ 'fastcgi_finish_request', 'fpm_get_status' ],
		'classes'   => [],
	],
	'posix'       => [
		'functions' => [
			'posix_access', 'posix_ctermid', 'posix_errno', 'posix_get_last_error',
			'posix_getcwd', 'posix_getegid', 'posix_geteuid', 'posix_getgid',
			'posix_getgrgid', 'posix_getgrnam', 'posix_getgroups', 'posix_getlogin',
			'posix_getpgid', 'posix_getpgrp', 'posix_getpid', 'posix_getppid',
			'posix_getpwnam', 'posix_getpwuid', 'posix_getrlimit', 'posix_getsid',
			'posix_getuid', 'posix_initgroups', 'posix_isatty', 'posix_kill',
			'posix_mkfifo', 'posix_mknod', 'posix_setegid', 'posix_seteuid',
			'posix_setgid', 'posix_setpgid', 'posix_setrlimit', 'posix_setsid',
			'posix_setuid', 'posix_strerror', 'posix_times', 'posix_ttyname',
			'posix_uname',
		],
		'classes'   => [],
	],
	'shmop'       => [
		'functions' => [ 'shmop_close', 'shmop_delete', 'shmop_open', 'shmop_read', 'shmop_size', 'shmop_write' ],
		'classes'   => [],
	],
	'sysvmsg'     => [
		'functions' => [ 'msg_get_queue', 'msg_queue_exists', 'msg_receive', 'msg_remove_queue', 'msg_send', 'msg_set_queue', 'msg_stat_queue' ],
		'classes'   => [ 'SysvMessageQueue' ],
	],
	'sysvsem'     => [
		'functions' => [ 'sem_acquire', 'sem_get', 'sem_release', 'sem_remove' ],
		'classes'   => [ 'SysvSemaphore' ],
	],
	'sysvshm'     => [
		'functions' => [ 'shm_attach', 'shm_detach', 'shm_get_var', 'shm_has_var', 'shm_put_var', 'shm_remove_var', 'shm_remove' ],
		'classes'   => [ 'SysvSharedMemory' ],
	],
	'pcntl'       => [
		'functions' => [
			'pcntl_alarm', 'pcntl_async_signals', 'pcntl_errno', 'pcntl_exec',
			'pcntl_fork', 'pcntl_get_last_error', 'pcntl_getpriority',
			'pcntl_rfork', 'pcntl_setpriority', 'pcntl_signal_dispatch',
			'pcntl_signal_get_handler', 'pcntl_signal', 'pcntl_sigprocmask',
			'pcntl_sigtimedwait', 'pcntl_sigwaitinfo', 'pcntl_strerror',
			'pcntl_unshare', 'pcntl_wait', 'pcntl_waitpid', 'pcntl_wexitstatus',
			'pcntl_wifcontinued', 'pcntl_wifexited', 'pcntl_wifsignaled',
			'pcntl_wifstopped', 'pcntl_wstopsig', 'pcntl_wtermsig',
		],
		'classes'   => [],
	],
	'readline'    => [
		'functions' => [
			'readline_add_history', 'readline_callback_handler_install',
			'readline_callback_handler_remove', 'readline_callback_read_char',
			'readline_clear_history', 'readline_completion_function',
			'readline_info', 'readline_list_history', 'readline_on_new_line',
			'readline_read_history', 'readline_redisplay', 'readline_write_history',
			'readline',
		],
		'classes'   => [],
	],
	'ssh2'        => [
		'functions' => [
			'ssh2_auth_agent', 'ssh2_auth_hostbased_file', 'ssh2_auth_none',
			'ssh2_auth_password', 'ssh2_auth_pubkey_file', 'ssh2_connect',
			'ssh2_exec', 'ssh2_fetch_stream', 'ssh2_fingerprint', 'ssh2_methods_negotiated',
			'ssh2_publickey_add', 'ssh2_publickey_init', 'ssh2_publickey_list',
			'ssh2_publickey_remove', 'ssh2_scp_recv', 'ssh2_scp_send',
			'ssh2_sftp_chmod', 'ssh2_sftp_lstat', 'ssh2_sftp_mkdir', 'ssh2_sftp_readlink',
			'ssh2_sftp_realpath', 'ssh2_sftp_rename', 'ssh2_sftp_rmdir', 'ssh2_sftp_stat',
			'ssh2_sftp_symlink', 'ssh2_sftp_unlink', 'ssh2_sftp', 'ssh2_shell',
			'ssh2_tunnel',
		],
		'classes'   => [],
	],
	'yaf'         => [ 'functions' => [], 'classes' => [ 'Yaf_Application', 'Yaf_Controller_Abstract', 'Yaf_Dispatcher' ] ],
	'oci8'        => [
		'functions' => [
			'oci_bind_array_by_name', 'oci_bind_by_name', 'oci_cancel', 'oci_client_version',
			'oci_close', 'oci_commit', 'oci_connect', 'oci_define_by_name', 'oci_error',
			'oci_execute', 'oci_fetch_all', 'oci_fetch_array', 'oci_fetch_assoc',
			'oci_fetch_object', 'oci_fetch_row', 'oci_fetch', 'oci_field_is_null',
			'oci_field_name', 'oci_field_precision', 'oci_field_scale', 'oci_field_size',
			'oci_field_type_raw', 'oci_field_type', 'oci_free_descriptor', 'oci_free_statement',
			'oci_get_implicit_resultset', 'oci_lob_copy', 'oci_lob_is_equal',
			'oci_new_collection', 'oci_new_connect', 'oci_new_cursor', 'oci_new_descriptor',
			'oci_num_fields', 'oci_num_rows', 'oci_parse', 'oci_password_change',
			'oci_pconnect', 'oci_result', 'oci_rollback', 'oci_server_version',
			'oci_set_action', 'oci_set_call_timeout', 'oci_set_client_identifier',
			'oci_set_client_info', 'oci_set_db_operation', 'oci_set_edition',
			'oci_set_module_name', 'oci_set_prefetch_lob_size', 'oci_set_prefetch',
			'oci_statement_type',
		],
		'classes'   => [ 'OCI_Lob', 'OCI_Collection' ],
	],
];