<?php
/**
 * Monetization Request Controller
 * 
 * @author Callistus Nwachukwu
 * @package SmartLicenseServer
 * @subpackage Monetization
 * @since 0.0.5 
 */

namespace SmartLicenseServer\Monetization;

use SmartLicenseServer\Core\Request;
use SmartLicenseServer\Core\Response;
use SmartLicenseServer\Core\URL;
use SmartLicenseServer\Exceptions\RequestException;
use SmartLicenseServer\HostedApps\HostedApplicationService;
use SmartLicenseServer\Security\SecurityAwareTrait;
use SmartLicenseServer\Utils\SanitizeAwareTrait;

defined( 'SMLISER_ABSPATH' ) || exit;

/**
 * Handles all requests related to software monetization
 */
class Controller {
    use SecurityAwareTrait, SanitizeAwareTrait;
    /**
     * Handles save monetization request by consuming a portable Request object.
     * 
     * @param Request $request The portable request object generated by the adapter.
     * @return Response The portable response object containing data or an exception.
     */
    public static function save_monetization( Request $request ): Response {
        try {
            $monetization_id = $request->get( 'monetization_id', 0 );
            $app_id         = $request->get( 'app_id', 0 );
            $tier_id         = $request->get( 'tier_id', 0 );
            $max_sites       = $request->get( 'max_sites', -1 );

            $app_type   = $request->get( 'app_type' )
                ?: throw new RequestException( 'missing_app_type', 'Item type is required', array( 'field_id' => 'app_type', 'status' => 400 ) );

            $tier_name   = $request->get( 'tier_name' )
                ?: throw new RequestException( 'missing_tier_name', 'Tier name is required', array( 'field_id' => 'tier_name', 'status' => 400 ) );

            $product_id  = $request->get( 'product_id' )
                ?: throw new RequestException( 'missing_product_id', 'Product ID is required', array( 'field_id' => 'product_id', 'status' => 400 ) );

            $billing_cycle = $request->get( 'billing_cycle' )
                ?: throw new RequestException( 'missing_billing_cycle', 'Billing cycle is required', array( 'field_id' => 'billing_cycle', 'status' => 400 ) );

            $provider_id = $request->get( 'provider_id' )
                ?: throw new RequestException( 'missing_provider_id', 'Please select a monetization provider', array( 'field_id' => 'provider_id', 'status' => 400 ) );

            $features    = $request->get( 'features' )
                ?: throw new RequestException( 'missing_features', 'Enter at least one feature', array( 'field_id' => 'features', 'status' => 400 ) );

            $features_array = array_map( 'trim', explode( ',', $features ) );

            if ( ! ProviderCollection::instance()->has_provider( $provider_id ) ) {
                throw new RequestException( 'invalid_provider', 'The selected monetization provider does not exist.', array( 'field_id' => 'provider_id', 'status' => 400 ) );
            }

            $app    = HostedApplicationService::get_app_by_id( $app_type, $app_id );

            if ( ! $app ) {
                throw new RequestException( 'app_not_found' );
            }

            static::check_app_ownership( $app );

            $monetization = Monetization::get_by_app( $app->get_type(), $app->get_id() ) ?: new Monetization();

            if ( ! $monetization->exists() ) {
                static::check_permissions( 'monetization.create' );

                $monetization->set_app_id( $app_id )
                    ->set_app_type( $app_type );
            } else {
                static::check_permissions( 'monetization.update' );
            }
            
            $pricing_tier = PricingTier::get_by_id( $tier_id ) ?? new PricingTier();

            if ( $pricing_tier->exists() ) {
                static::check_permissions( 'monetization.pricing.update' );
            } else {
                static::check_permissions( 'monetization.pricing.create' );
            }

            $pricing_tier->set_monetization_id( $monetization_id )
                ->set_id( $tier_id )
                ->set_name( $tier_name )
                ->set_product_id( $product_id )
                ->set_billing_cycle( $billing_cycle )
                ->set_provider_id( $provider_id )
                ->set_max_sites( $max_sites )
                ->set_features( $features_array );

            $monetization->add_tier( $pricing_tier );

            if ( $monetization->save() ) {

                $response_data = [ 'success' => true, 'data' => [ 'message' => 'Saved' ] ];
                return ( new Response( 200, [], smliser_safe_json_encode( $response_data ) ) )
                    ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
            }

            throw new RequestException( 'save_failed', 'Something went wrong during data persistence.', array( 'status' => 500 ) );

        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }
    }

    /**
     * Handle delete monetization tier request.
     * 
     * @param Request $request
     * @return Response
     */
    public static function delete_monetization_tier( Request $request ) : Response {
        try {
            static::check_permissions( 'monetization.pricing.delete' );
            
            $monetization_id = $request->get( 'monetization_id', 0 );
            $tier_id         = $request->get( 'tier_id', 0 );

            if ( ! $monetization_id ) {
                throw new RequestException( 'invalid_input', __( 'Monetization ID is required.', 'smliser' ), ['status' => 400] );
            }

            if ( ! $tier_id ) {
                throw new RequestException( 'invalid_input', __( 'Tier ID is required.', 'smliser' ), ['status' => 400] );
            }

            $monetization = Monetization::get_by_id( $monetization_id );

            if ( ! $monetization ) {
                throw new RequestException( 'resource_not_found', __( 'Monetization not found.', 'smliser' ), ['status' => 404] );
            }

            $app    = $monetization->get_app();
            if ( $app ) static::check_app_ownership( $app );
            
            $deleted = $monetization->delete_tier( $tier_id );

            if ( ! $deleted ) {
                throw new RequestException( 'resource_not_found', __( 'Failed to delete the pricing tier, please try again.', 'smliser' ), ['status' => 500] );
            }
            $response_data = [ 'success' => true, 'data' => [ 'message' => 'Pricing tier deleted successfully.'] ];
            return ( new Response( 200, [], smliser_safe_json_encode( $response_data ) ) )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );

        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }
    }

    /**
     * Handle request to fetch provider product data.
     * 
     * @param Request $request
     * @return Response
     */
    public static function get_provider_product( Request $request ) : Response {

        try {
            $provider_id = $request->get( 'provider_id' );
            $product_id  = $request->get( 'product_id' );

            if ( ! $provider_id ) {
                throw new RequestException( 'required_param', __( 'Provider ID is required.', 'smliser' ), ['status' => 400] );
            }

            if ( ! $product_id ) {
                throw new RequestException( 'required_param', __( 'Product ID is required.', 'smliser' ), ['status' => 400] );
            }

            $provider   = ProviderCollection::instance()->get_provider( $provider_id );
            
            if ( ! $provider ) {
                throw new RequestException( 'resource_not_found', __( 'Invalid provider specified.', 'smliser' ), ['status' => 404] );
            }
            $product = $provider->get_product( $product_id );

            if ( ! $product ) {
                throw new RequestException( 'resource_not_found', __( 'Product not found from provider.', 'smliser' ), ['status' => 404] );
            }

            $valid_product = ProviderCollection::validate_product_data( $product );

            if ( is_smliser_error( $valid_product ) ) {
                throw new RequestException( $valid_product->get_error_code(), $valid_product->get_error_message(), ['status' => 500] );
            }

            $response_data = [
                'success' => true, 
                'data' => [
                    'message' => 'Saved',
                    'product' => $valid_product,
                ]
            ];
            return ( new Response( 200, [], smliser_safe_json_encode( $response_data ) ) )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );


        } catch ( RequestException $e) {
            return ( new Response() )
                ->set_exception( $e )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }
    }

    /**
     * Handle monetization status toggling
     * 
     * @param Request $request
     */
    public static function toggle_monetization( Request $request ) : Response {

        try {
            
            static::check_permissions( 'change_status' );

            $monetization_id = $request->get( 'monetization_id' );
            $enabled         = $request->getTyped( 'enabled', 'boolean', false );

            if ( ! $monetization_id ) {
                throw new RequestException( 'invalid_input', __( 'This monetization does not exist yet, please add a pricing tier first.', 'smliser' ), ['status' => 400] );
            }

            $monetization = Monetization::get_by_id( $monetization_id );

            if ( ! $monetization ) {
                throw new RequestException( 'resource_not_found', __( 'Monetization not found.', 'smliser' ), ['status' => 404] );
            }

            $app    = $monetization->get_app();

            if ( $app ) static::check_app_ownership( $app );

            $monetization->set_enabled( $enabled );
            $monetization->save();

            $message        =  $enabled ? __( 'Monetization enabled successfully.', 'smliser' ) : __( 'Monetization disabled successfully.', 'smliser' );
            $response_data = [ 'success' => true, 'data' => [ 'message' => $message ] ];
            return ( new Response( 200, [], smliser_safe_json_encode( $response_data ) ) )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }

    }

    /**
     * Process license save request
     * 
     * @param Request $request The Request object.
     * @return Response 
     */
    public static function save_license( Request $request ) : Response {
        try {
            $id                     = $request->get( 'license_id' );
            $service_id             = $request->get( 'service_id' );
            $status                 = $request->get( 'status' );
            $start_date             = $request->get( 'start_date' );
            $end_date               = $request->get( 'end_date' );
            $app_type               = $request->get( 'app_type', '' );
            $app_slug               = $request->get( 'app_slug', '' );
            $max_allowed_domains    = $request->get( 'max_allowed_domains', -1 );
            $licensee_fullname      = $request->get( 'licensee_fullname' );

            if ( '' === $max_allowed_domains ) {
                $max_allowed_domains = -1;
            } elseif ( (int) $max_allowed_domains < 0 ) {
                $max_allowed_domains = -1;
            }

            if ( ! empty( $app_slug ) && ! empty( $app_type ) ) {
                $app_prop   = sprintf( '%s/%s', $app_type, $app_slug );
            } else {
                $app_prop   = '';
            }

            $data   = compact(
                'id', 'service_id', 'max_allowed_domains',
                'service_id', 'status', 'start_date', 'end_date', 'app_prop',
                'licensee_fullname'
            );

            $license        = License::from_array( $data );
            $license_exists = $license->exists();

            if ( $license_exists ) {
                static::check_permissions( 'monetization.license.update' );
            } else {
                static::check_permissions( 'monetization.license.create' );
            }

            $app    = $license->get_app();
            if ( $app ) {
                static::check_app_ownership( $app );
                static::check_permissions( 'monetization.license.issue' );
            }

            if ( ! $license->save() ) {
                throw new RequestException( 'license_error', 'Unable to save the license' );
            }

            $request->set( 'license', $license );

            $response_data   = [
                'success'   => true,
                'message'   => sprintf( 'License %s successfully.', $license_exists ? 'Updated' : 'Created' ),
                'license'   => $license->to_array()
            ];
            $code   = $license_exists ? 200 : 201;
            $url    = new URL( smliser_license_admin_action_page( 'edit', $license->get_id() ) );
            $url->add_query_param( 'message', 'Saved' );

            $response = new Response( $code, [], $response_data );
            $response->set_header( 'Content-Type', 'application/json; charset=utf-8' )
            ->set_header( 'Location', $url->get_href() );

            return $response;
        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e );
        }
    }

    /**
     * License bulk action.
     * 
     * @param Request $request The request object.
     * @return Response
     */
    public static function license_bulk_action( Request $request ) : Response {
        try {
            // Only system admin can run bulk action.
            static::is_system_admin();

            $license_ids    = $request->get( 'ids', [] );
            $action         = $request->get( 'bulk_action' );
            $affected       = 0;

            foreach( (array) $license_ids as $id ) {
                $license    = License::get_by_id( $id );

                if ( ! $license ) {
                    continue;
                }

                if ( 'delete' === strtolower( $action ) ) {
                    $license->delete() && $affected++;
                    continue;
                }

                $license->set_status( $action );
                $license->save() && $affected++;
            }

            $url    = new URL( smliser_license_page() );
            $url->add_query_param( 'message', \sprintf( '%s affected!', $affected ) );
            
            $response = ( new Response( 200, [], '' ) )
                ->set_header( 'Location', $url->get_href() );

            return $response;            
        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e );
        }

    }

    /**
     * Save Monetization Provider options.
     * 
     * @param Request $request
     */
    public static function save_provider_options( Request $request ) : Response {

        try {

            static::is_system_admin();
            
            $provider_id = $request->get( 'provider_id', null );

            if ( ! $provider_id || ! ProviderCollection::instance()->has_provider( $provider_id ) ) {
                throw new RequestException( 'access_restricted', sprintf( 'The provider "%s" is not supported.', $provider_id ?? 'Unknown' ), [ 'status' => 403] );
            }

            $provider           = ProviderCollection::instance()->get_provider( $provider_id );
            $allowed_options    = array_keys( (array) $provider->get_allowed_options() );

            foreach( $allowed_options as $name ) {
                if ( $value = smliser_get_post_param( $name, null ) ) {
                    ProviderCollection::update_option( $provider->get_id(), $name, $value );
                } else {
                    ProviderCollection::update_option( $provider->get_id(), $name, '' );
                }
            }

            $response_data = [ 'success' => true, 'data' => [ 'message' => 'Saved' ] ];
            return ( new Response( 200, [], smliser_safe_json_encode( $response_data ) ) )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
            
        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }

    }

    /**
     * Remove/Uninstall a domain from a license
     * 
     * @param Request $request The request object.
     * @return Response
     */
    public static function uninstall_domain_from_license( Request $request ) : Response {
        try {
            static::check_permissions( 'monetization.license.uninstall_domain' );

            $license_id = $request->get( 'license_id' );
            $domain     = $request->get( 'domain' );

            if ( ! $license_id ) {
                throw new RequestException( 'invalid_input', __( 'License ID is required.', 'smliser' ), ['status' => 400] );
            }

            if ( ! $domain ) {
                throw new RequestException( 'invalid_input', __( 'Provide the domain to uninstall.', 'smliser' ), ['status' => 400] );
            }

            $license    = License::get_by_id( $license_id );

            if ( ! $license ) {
                throw new RequestException( 'resource_not_found', __( 'This license does not exist.', 'smliser' ), ['status' => 404] );
            }

            $app    = $license->get_app();

            if ( $app ) static::check_app_ownership( $app );

            if ( $license->is_new_domain( $domain ) ) {
                throw new RequestException( 'is_new_domain', __( 'The domain provided does not exist in this license.', 'smliser' ), ['status' => 404] );
            }

            $removed    = $license->remove_activated_domain( $domain );
            $message    = $removed ? \sprintf( 'The domain "%s" has been uninstalled', $domain ) : \sprintf( 'Unable to uninstall "%s"', $domain );
            

            $response_data = [ 'success' => true, 'data' => [ 'message' => $message ] ];
            return ( new Response( 200, [], smliser_safe_json_encode( $response_data ) ) )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }  catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }
    }
}