<?php
/**
 * Monetization Request Controller
 * 
 * @author Callistus Nwachukwu
 * @package SmartLicenseServer
 * @subpackage Monetization
 * @since 0.0.5 
 */

namespace SmartLicenseServer\Monetization;

use SmartLicenseServer\Core\Request;
use SmartLicenseServer\Core\Response;
use SmartLicenseServer\Exceptions\RequestException;

defined( 'SMLISER_ABSPATH' ) || exit;

/**
 * Handles all requests related to software monetization
 */
class Controller {
    /**
     * Handles save monetization request by consuming a portable Request object.
     * 
     * @param Request $request The portable request object generated by the adapter.
     * @return Response The portable response object containing data or an exception.
     */
    public static function save_monetization( Request $request ): Response {
        try {
            // Authorization Check (Defense-in-depth: Adapter should enforce this, but we check the flag)
            if ( ! $request->is_authorized() ) {
                throw new RequestException( 'unauthorized_access', 'You do not have permission to perform this action', array( 'status' => 403 ) );
            }

            $monetization_id = $request->get( 'monetization_id', 0 );
            $item_id         = $request->get( 'item_id', 0 );
            $tier_id         = $request->get( 'tier_id', 0 );
            $max_sites       = $request->get( 'max_sites', -1 );

            $item_type   = $request->get( 'item_type' )
                ?: throw new RequestException( 'missing_item_type', 'Item type is required', array( 'field_id' => 'item_type', 'status' => 400 ) );

            $tier_name   = $request->get( 'tier_name' )
                ?: throw new RequestException( 'missing_tier_name', 'Tier name is required', array( 'field_id' => 'tier_name', 'status' => 400 ) );

            $product_id  = $request->get( 'product_id' )
                ?: throw new RequestException( 'missing_product_id', 'Product ID is required', array( 'field_id' => 'product_id', 'status' => 400 ) );

            $billing_cycle = $request->get( 'billing_cycle' )
                ?: throw new RequestException( 'missing_billing_cycle', 'Billing cycle is required', array( 'field_id' => 'billing_cycle', 'status' => 400 ) );

            $provider_id = $request->get( 'provider_id' )
                ?: throw new RequestException( 'missing_provider_id', 'Please select a monetization provider', array( 'field_id' => 'provider_id', 'status' => 400 ) );

            $features    = $request->get( 'features' )
                ?: throw new RequestException( 'missing_features', 'Enter at least one feature', array( 'field_id' => 'features', 'status' => 400 ) );

            $features_array = array_map( 'trim', explode( ',', $features ) );

            if ( ! ProviderCollection::instance()->has_provider( $provider_id ) ) {
                throw new RequestException( 'invalid_provider', 'The selected monetization provider does not exist.', array( 'field_id' => 'provider_id', 'status' => 400 ) );
            }

            $monetization = Monetization::get_by_app( $item_type, $item_id ) ?: new Monetization();
            $monetization->set_item_id( $item_id )
                        ->set_item_type( $item_type );

            $pricing_tier = PricingTier::get_by_id( $tier_id ) ?: new PricingTier();
            $pricing_tier->set_monetization_id( $monetization_id )
                        ->set_id( $tier_id )
                        ->set_name( $tier_name )
                        ->set_product_id( $product_id )
                        ->set_billing_cycle( $billing_cycle )
                        ->set_provider_id( $provider_id )
                        ->set_max_sites( $max_sites )
                        ->set_features( $features_array );

            $monetization->add_tier( $pricing_tier );

            if ( $monetization->save() ) {
                // Success response: return portable Response object
                $response_data = [ 'success' => true, 'data' => [ 'message' => 'Saved' ] ];
                return ( new Response( 200, [], smliser_safe_json_encode( $response_data ) ) )
                    ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
            }

            throw new RequestException( 'save_failed', 'Something went wrong during data persistence.', array( 'status' => 500 ) );

        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e )
                ->set_header( 'Content-Type', 'application/json; charset=utf-8' );
        }
    }

    /**
     * Handle delete monetization tier request.
     */
    public static function delete_monetization_tier() {
        if ( ! check_ajax_referer( 'smliser_nonce', 'security', false ) ) {
            smliser_send_json_error( array(
                'message'  => 'This action failed basic security check.',
                'field_id' => 'security',
            ), 401 );
        }

        if ( ! current_user_can( 'manage_options' ) ) {
            smliser_send_json_error( array(
                'message'  => 'You do not have permission to perform this action.',
            ), 403 );
        }

        $monetization_id = smliser_get_post_param( 'monetization_id', 0 );
        $tier_id         = smliser_get_post_param( 'tier_id', 0 );

        if ( ! $monetization_id ) {
            smliser_send_json_error( array(
                'message'  => 'Monetization ID is required.',
                'field_id' => 'monetization_id',
            ), 400 );
        }

        if ( ! $tier_id ) {
            smliser_send_json_error( array(
                'message'  => 'Tier ID is required.',
                'field_id' => 'tier_id',
            ), 400 );
        }

        $monetization = Monetization::get_by_id( $monetization_id );
        if ( ! $monetization ) {
            smliser_send_json_error( array(
                'message'  => 'The specified monetization record does not exist.',
            ), 404 );
        }

        $deleted = $monetization->delete_tier( $tier_id );

        if ( ! $deleted ) {
            smliser_send_json_error( array(
                'message'  => 'Failed to delete the pricing tier. Please try again.',
            ), 500 );
        }

        smliser_send_json_success( array(
            'message' => 'Pricing tier deleted successfully.',
        ) );
    }

    /**
     * Handle Ajax request to fetch provider product data.
     *
     * @return void
     */
    public static function get_provider_product() {

        if ( ! check_ajax_referer( 'smliser_nonce', 'security', false ) ) {
            smliser_send_json_error( array(
                'message'  => 'This action failed basic security check.',
                'field_id' => 'security',
            ), 401 );
        }

        $provider_id = smliser_get_query_param( 'provider_id' );
        $product_id  = smliser_get_query_param( 'product_id' );

        if ( empty( $provider_id ) ) {
            smliser_send_json_error( array(
                'message'  => __( 'Provider ID is required.', 'smliser' ),
                'field_id' => 'provider_id',
            ) );
        }

        if ( empty( $product_id ) ) {
            smliser_send_json_error( array(
                'message'  => __( 'Product ID is required.', 'smliser' ),
                'field_id' => 'product_id',
            ) );
        }

        // Resolve provider
        $provider = ProviderCollection::instance()->get_provider( $provider_id );
        
        if ( ! $provider ) {
            smliser_send_json_error( array(
                'message' => __( 'Invalid provider specified.', 'smliser' ),
                'field_id' => 'provider_id',
            ) );
        }

        // Fetch product data
        $product = $provider->get_product( $product_id );
        
        if ( empty( $product ) ) {
            smliser_send_json_error( array(
                'message' => __( 'Product not found from provider.', 'smliser' ),
                'field_id' => 'product_id',
            ) );
        }

        $valid_product = ProviderCollection::validate_product_data( $product );

        if ( is_smliser_error( $valid_product ) ) {
            smliser_send_json_error( array(
                'message' => $valid_product->get_error_message(),
            ) );
        }

        smliser_send_json_success( array(
            'message' => __( 'Product data retrieved successfully.', 'smliser' ),
            'product' => $valid_product,
        ) );
    }

    /**
     * Handle monetization status toggling
     */
    public static function toggle_monetization() {

        if ( ! check_ajax_referer( 'smliser_nonce', 'security', false ) ) {
            smliser_send_json_error( array(
                'message'  => __( 'Security check failed.', 'smliser' ),
                'field_id' => 'security',
            ), 401 );
        }

        $monetization_id = absint( smliser_get_post_param( 'monetization_id' ) );
        $enabled         = absint( smliser_get_post_param( 'enabled' ) );

        if ( ! $monetization_id ) {
            smliser_send_json_error( array(
                'message'  => __( 'This monetization does not exist yet, please add a pricing tier first.', 'smliser' ),
                'field_id' => 'monetization_id',
            ) );
        }

        $monetization = Monetization::get_by_id( $monetization_id );
        if ( ! $monetization ) {
            smliser_send_json_error( array(
                'message'  => __( 'Monetization not found.', 'smliser' ),
                'field_id' => 'monetization_id',
            ) );
        }

        $monetization->set_enabled( $enabled );
        $monetization->save();

        smliser_send_json_success( array(
            'message' => $enabled
                ? __( 'Monetization enabled successfully.', 'smliser' )
                : __( 'Monetization disabled successfully.', 'smliser' ),
        ) );
    }

    /**
     * Process license save request
     * 
     * @param Request $request The Request object.
     * @return Response 
     */
    public static function save_license( Request $request ) : Response {
        try {
            $id                     = $request->get( 'license_id' );
            $user_id                = $request->get( 'user_id' );
            $service_id             = $request->get( 'service_id' );
            $status                 = $request->get( 'status' );
            $start_date             = $request->get( 'start_date' );
            $end_date               = $request->get( 'end_date' );
            $app_prop               = $request->get( 'app_prop', '' );
            $max_allowed_domains    = $request->get( 'max_allowed_domains', -1 );

            if ( '' === $max_allowed_domains ) {
                $max_allowed_domains = -1;
            } elseif ( (int) $max_allowed_domains < 0 ) {
                $max_allowed_domains = -1;
            }

            if ( ! empty( $app_prop ) ) {
                $app_prop   = \str_replace( ':', '/', $app_prop );
            }

            $data       = compact( 'id', 'user_id', 'service_id', 'max_allowed_domains', 'service_id', 'status', 'start_date', 'end_date', 'app_prop' );
            
            $license    = License::from_array( $data );

            if ( ! $license->save() ) {
                throw new RequestException( 'license_error', 'Unable to save the license' );
            }

            $request->set( 'license', $license );

            $response = new Response();
            $response->set_response_data( $request );

            return $response;
        } catch ( RequestException $e ) {
            return ( new Response() )
                ->set_exception( $e );
        }
    }

    /**
     * License bulk action.
     * 
     * @param Request $request The request object.
     * @return Response
     */
    public static function license_bulk_action( Request $request ) : Response {
        $license_ids    = $request->get( 'license_ids', [] );
        $action         = $request->get( 'bulk_action' );
        $affected       = 0;

        foreach( (array) $license_ids as $id ) {
            $license    = License::get_by_id( $id );

            if ( ! $license ) {
                continue;
            }

            if ( 'delete' === strtolower( $action ) ) {
                $license->delete() && $affected++;
                continue;
            }

            $license->set_status( $action );
            $license->save() && $affected++;
        }

        $request->set( 'message', \sprintf( '%s affected!', $affected ) );
        $response = ( new Response( 200, [], '' ) )
            ->set_response_data( $request );

        return $response;
    }

}